on: workflow_dispatch
name: deploy-heroku
jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: '8.10.7'
          cabal-version: '3.6.2.0'
      - run: cabal update
      - run: cabal freeze
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
          key: cabal-store-${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            cabal-store-${{ runner.os }}-
      - run: cabal build -O2 exe:significant-figures-web
      - run: mkdir -p ../heroku-repo
      # - uses: lhotari/action-upterm@v1
      - run: mv dist-newstyle/build/x86_64-linux/ghc-8.10.7/significant-figures-0.1.0.0/x/significant-figures-api/opt/build/significant-figures-api/significant-figures-api ../heroku-repo/sigfig-api
      - run: cp Procfile ../heroku-repo
      - run: |
         cd ../heroku-repo

         git init
         git config user.email "${{ secrets.GIT_EMAIL }}"
         git config user.name "${{ secrets.GIT_NAME }}"
         git add .
         git commit -m "deploying"

         git push -f "${{ secrets.HEROKU_APP_GIT_URL }}" HEAD:main
