on: [push]
name: build
jobs:
  build:
    name: Build for OSes
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '8.10.7'
          cabal-version: '3.6.2.0'
      - run: cabal update
      - run: cabal build --disable-optimization
      - run: ls -R
